### ISSUE TITLE
InvalidInputDatatype: Input of type 'Unknown' is not supported. Supported types: [azureml.data.tabular_dataset.TabularDataset, azureml.pipeline.core.pipeline_output_dataset.PipelineOutputTabularDataset]

### ISSUE THREAD

**Issue by marciomocellin** [MicrosoftDocs/azure-docs.pt-br#623]
Eu tenho um DataFrame do pandas criado assim:

```python
TB_HISTORICO_MODELO = pd.read_sql("""select DAT_INICIO_SEMANA_PLAN
,COD_NEGOCIO
,VENDA
,LUCRO
,MODULADO
,RUPTURA
,QTD_ESTOQUE_MEDIO
,PECAS from TB""", cursor)

TB_HISTORICO_MODELO["DAT_INICIO_SEMANA_PLAN"] = pd.to_datetime(TB_HISTORICO_MODELO["DAT_INICIO_SEMANA_PLAN"])

dataset = TB_HISTORICO_MODELO[TB_HISTORICO_MODELO['COD_NEGOCIO']=='A101'].drop(columns=['COD_NEGOCIO']) .reset_index(drop=True)
```
tudo me parece certo. 

```python
>>> dataset.dtypes
DAT_INICIO_SEMANA_PLAN    datetime64[ns]
VENDA                            float64
LUCRO                            float64
MODULADO                           int64
RUPTURA                            int64
QTD_ESTOQUE_MEDIO                  int64
PECAS                            float64
dtype: object
```

Mas quando executo a parte final:

```python
#%% Create the AutoML Config file and run the experiment on Azure

from azureml.train.automl import AutoMLConfig

time_series_settings = {
   'time_column_name': 'DAT_INICIO_SEMANA_PLAN',
   'max_horizon': 14,
   'country_or_region': 'BR',
   'target_lags': 'auto'
}

automl_config = AutoMLConfig(task='forecasting',
                            primary_metric='normalized_root_mean_squared_error',
                            blocked_models=['ExtremeRandomTrees'],
                            experiment_timeout_minutes=30,
                            training_data=dataset,
                            label_column_name='VENDA',
                            compute_target = compute_cluster,
                            enable_early_stopping=True,
                            n_cross_validations=3,
                            # max_concurrent_iterations=4,
                            # max_cores_per_iteration=-1,
                            verbosity=logging.INFO,
                            **time_series_settings)

remote_run = Experimento.submit(automl_config, show_output=True)
```
Recebo esta resposta:

```python
>>> remote_run = Experimento.submit(automl_config, show_output=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fnord/venv/lib64/python3.6/site-packages/azureml/core/experiment.py", line 219, in submit
    run = submit_func(config, self.workspace, self.name, **kwargs)
  File "/home/fnord/venv/lib64/python3.6/site-packages/azureml/train/automl/automlconfig.py", line 92, in _automl_static_submit
    automl_config_object._validate_config_settings(workspace)
  File "/home/fnord/venv/lib64/python3.6/site-packages/azureml/train/automl/automlconfig.py", line 1775, in _validate_config_settings
    supported_types=", ".join(SupportedInputDatatypes.REMOTE_RUN_SCENARIO)
azureml.train.automl.exceptions.ConfigException: ConfigException:
        Message: Input of type 'Unknown' is not supported. Supported types: [azureml.data.tabular_dataset.TabularDataset, azureml.pipeline.core.pipeline_output_dataset.PipelineOutputTabularDataset]
        InnerException: None
        ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Input of type 'Unknown' is not supported. Supported types: [azureml.data.tabular_dataset.TabularDataset, azureml.pipeline.core.pipeline_output_dataset.PipelineOutputTabularDataset]",
        "details_uri": "https://aka.ms/AutoMLConfig",
        "target": "training_data",
        "inner_error": {
            "code": "BadArgument",
            "inner_error": {
                "code": "ArgumentInvalid",
                "inner_error": {
                    "code": "InvalidInputDatatype"
                }
            }
        }
    }
}

```
Oque estou fazendo de errado?

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 585fff5e-cadd-8967-8c09-63d8afcb53b3
* Version Independent ID: 95274303-b152-2ee8-113e-e0763beca7ed
* Content: [Criar experimentos de ML automatizados - Azure Machine Learning](https://docs.microsoft.com/pt-br/azure/machine-learning/how-to-configure-auto-train#configure-your-experiment-settings)
* Content Source: [articles/machine-learning/how-to-configure-auto-train.md](https://github.com/MicrosoftDocs/azure-docs.pt-br/blob/master/articles/machine-learning/how-to-configure-auto-train.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @cartacioS
* Microsoft Alias: **sacartac**

**Comment by marciomocellin** [comment]
Is anyone here?

**Comment by nibaccam** [comment]
Hi @marciomocellin apologies for the delay. The issue you filed is in Portuguese, so I want to make sure I'm understanding the scenario. You have a pandas dataframe created from a SQL table, but when you submitted the run for your experiment you got an error saying your data type isn't supported. Is this correct? 

Could you also let me know what version of the Python SDK you are running, please?

**Comment by nibaccam** [comment]
@marciomocellin we haven't heard from you lately. If you no longer require assistance, please close this thread. 

#please-close
